name: Semantic Release

on:
  pull_request:
    types:
      - labeled
    branches:
      - 'main'

jobs:
  release:
    if: ${{ github.event.label.name == 'semantic versioning' }}
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0


    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}